import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Menu from './components/menu'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: ' CoffeeBreakLoans.com™ Official Site. As Seen on TikTok ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Script id="show-banner">
        {` var _lg_form_init_ = {
      aid: "13405",
      template: "elvis-us",
    }`}
      </Script>
      <Script
        type="text/javascript"
        async={true}
        src="https://loansaccount.com/form/applicationInit.js"
      ></Script>
      <body className={inter.className}>
        <Menu />
        {children}
        <Footer />
      </body>
    </html>
  )
}
